services:
  - type: web
    name: php-product-store
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Farzad_db   # ← با F بزرگ
          property: connectionString
