services:
  - type: web
    name: my-php-app
    runtime: php
    plan: free
    buildCommand: ./build.sh
    startCommand: php -S 0.0.0.0:10000 -t .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString

    phpVersion: 8.2